export tag=v1.0-metrics

build:
	echo "building httpserver container"
	docker build -t wupanfeng035/httpserver:${tag} .

push:
	echo "pushing wupanfeng035/httpserver"
	docker push wupanfeng035/httpserver:${tag}
